version: '3.4'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=${PUID} # comment out if you don't need this
      - PGID=${PGID}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - c=${c} # comment out if you don't need this
      - test=${test}
    volumes:
      - /path/to/data:/config
      - /path/to/directory/web:/etc/ssl/web
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - c=${c}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - speedtest-db:/var/lib/postgresql/data
  random:
    image: postgres:15
    restart: always
    volumes:
      - speedtest-db:/var/lib/postgresql/data

volumes:
  speedtest-db:
