version: "3.4"
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=10001 # comment out if you don't need this
      - PGID=1000
      - DB_CONNECTION=pgsq
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=password
    volumes:
      - /path/to/data:/config
      - /path/to/directory/web:/etc/ssl/web
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=speedy
      - POSTGRES_PASSWORD=password
    volumes:
      - speedtest-db:/var/lib/postgresql/data
volumes:
  speedtest-db:
